version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    hostname: redis
    command: redis-server --save "" --appendonly no --maxclients 2000
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "150MB"